export const BOOKING_CREATE = 'BOOKING_CREATE';
export const BOOKING_UPDATE = 'BOOKING_UPDATE';
export const BOOKING_DELETE = 'BOOKING_DELETE';
export const BOOKING_DELETE_ALL = 'BOOKING_DELETE_ALL';
export const BOOKING_FETCH_ALL = 'BOOKING_FETCH_ALL';
export const BOOKING_FETCH_ALL_BY_CLINIC = 'BOOKING_FETCH_ALL_BY_CLINIC';
