export const CLINIC_CREATE = 'CLINIC_CREATE';
export const CLINIC_UPDATE = 'CLINIC_UPDATE';
export const CLINIC_DELETE = 'CLINIC_DELETE';
export const CLINIC_DELETE_ALL = 'CLINIC_DELETE_ALL';
export const CLINIC_FETCH_ALL = 'CLINIC_FETCH_ALL';
