export const DOCTOR_CREATE = 'DOCTOR_CREATE';
export const DOCTOR_UPDATE = 'DOCTOR_UPDATE';
export const DOCTOR_DELETE = 'DOCTOR_DELETE';
export const DOCTOR_DELETE_ALL = 'DOCTOR_DELETE_ALL';
export const DOCTOR_FETCH_ALL = 'DOCTOR_FETCH_ALL';
