export const SETTING_CREATE = 'SETTING_CREATE';
export const SETTING_UPDATE = 'SETTING_UPDATE';
export const SETTING_DELETE = 'SETTING_DELETE';
export const SETTING_DELETE_ALL = 'SETTING_DELETE_ALL';
export const SETTING_FETCH_ALL = 'SETTING_FETCH_ALL';
